### ISSUE TITLE
[MarioKart] Plugin MarioKart v9 generated an exception while executing task 398309

### ISSUE THREAD

**Issue by blakedj012** [Jakllp/MarioKart-1.16plus#1]
Many Thanks for this Plugin. I have following error.

[16:31:26 WARN]: [MarioKart] Plugin MarioKart v9 generated an exception while executing task 398309
java.lang.NullPointerException: null
        at net.stormdev.mario.utils.SerializableLocation.returnLocation(SerializableLocation.java:32) ~[?:?]
        at net.stormdev.mario.powerups.TrackingShellPowerup.calculateVelocity(TrackingShellPowerup.java:136) ~[?:?]
        at net.stormdev.mario.powerups.TrackingShellPowerup.move(TrackingShellPowerup.java:78) ~[?:?]
        at net.stormdev.mario.powerups.TrackingShellPowerup$2.run(TrackingShellPowerup.java:266) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-445]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-445]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-445]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

Latest Paper 1.16.5

**Comment by Jakllp** [comment]
Weißt, du, was du getan hast als der Fehler passiert ist?

**Comment by blakedj012** [comment]
Hast Du Discord oder sowas? Da könnte man effizienter schreiben. ^^

Und ich bin nur gefahren und hab mich ab und zu respawnen müssen wegen den Slaps wo er ab und zu stecken bleibt.

**Comment by Jakllp** [comment]
Discord: Jakl#9958

**Comment by Jakllp** [comment]
Fixed in latest version
